### ISSUE TITLE
Unknown prop warnings in React v15

### ISSUE THREAD

**Issue by Dermah** [tcoopman/react-flexbox#11]
React v15 has started warning about [adding unknown props to DOM elements](https://fb.me/react-unknown-prop)

Using `react-flexbox` with React v15 prints lots of warnings because props for `View` like `auto`, `column`, `row` etc. are being added as props to the underlying `div`. For example:

```
Warning: Unknown prop `auto` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div
    in View (created by Component)
...
```

**Comment by SlowburnAZ** [comment]
Same issue here with React v15
