### ISSUE TITLE
"undefined is not a function" on usage

### ISSUE THREAD

**Issue by SkaveRat** [tcoopman/react-flexbox#2]
Error is thrown in the `autoGenerateWrapperClass` function of react, on the `tagName: type.toUpperCase()` line.

any idea what causes this?

I've installed react-flexbox via npm, using the latest version, and I'm importing via:
`View = require('react-flexbox')`

**Comment by tcoopman** [comment]
This should be fixed in 2.0.0. Can you check please?

**Comment by SkaveRat** [comment]
Still the same problem

**Comment by tcoopman** [comment]
Can you give me some code where you have the problem?
