### ISSUE TITLE
Ability to set flex-basis

### ISSUE THREAD

**Issue by RangerMauve** [tcoopman/react-flexbox#5]
I've currently got a bug integrating this with a [material-ui table](http://material-ui.com/#/components/table). What happens is that the table stretches in width infinitely across the screen (gets capped at some very large number). If I manually set the flex-basis to a non-0 value, it fills in properly, however.

It'd be nice to be able to set a flexGrow value as a prop to account for situations like this

**Comment by tcoopman** [comment]
Can you give a concrete code example of how you'd want it to behave?

**Comment by RangerMauve** [comment]
Well, really, I think it'd be as easy as just having a new prop called `grow` which would override the default setting for `flex-grow`

**Comment by tcoopman** [comment]
Hmm, I need to think this through. Basicly what API I want to support on the component and what not.

**Comment by RangerMauve** [comment]
Yeah, I can see how it'd be hard to abstract it nicely away when there's a lot of properties to deal with. Maybe it'd be useful to be able to add a class name to the elements to customize them further, or pass in a style prop?

**Comment by tcoopman** [comment]
At the moment you can set the className and style if you wish.

**Comment by RangerMauve** [comment]
Oh, I didn't know that. That's pretty useful.

**Comment by tcoopman** [comment]
Let me know if that fixes it for you
