### ISSUE TITLE
Some thoughts about composition

### ISSUE THREAD

**Issue by sergey-lapin** [tcoopman/react-flexbox#6]
Hi! Thanks for this package - very helpful=)

I noticed that quite often I need something like that.

```
const orientation = {row:trueOrFalse, trueOrFalse}
const itemsOrientation = {row:trueOrFalse, column:trueOrFalse}

<View {..orientation}>
    <View {..itemsOrientation}></View>
    <View {..itemsOrientation}></View>
  </View>
```

As it explotates awesome feature of flexbox - you can get 4 types of items composition for free. 
column list, row list, and two tables.

I think there is a potential here, what do you think?

**Comment by tcoopman** [comment]
Yeah that looks useful but I'm not sure about the best API for this and I'm wondering if you can do just with `style`. You should be able to do `<View style={..orientation}>`

Do you have any thoughts?

**Comment by tcoopman** [comment]
Closing because no  response.
